import newBan from "./components/ImgFolder/newBan.jpg";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/banner.module.css";
import dog1 from "./components/ImgFolder/dog1.jpg";
import dog2 from "./components/ImgFolder/dog2.jpg";
import dog3 from "./components/ImgFolder/dog3.jpg";
import dog4 from "./components/ImgFolder/dog4.jpg";
import PetLink from "./PetLink";
import FormatQuoteIcon from "@mui/icons-material/FormatQuote";
import ModalPopUps from "./ModalPopUps";
import { useState } from "react";

export default function Home() {
  const handleClick = (e) => {
    <Link href="/Pets"></Link>;
  };
  const [popOut, setPopOut] = useState(false);
  const handlePopUps = (e) => {
    setPopOut(true);
  };
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Petinder</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
          <link
            href="https://fonts.googleapis.com/css2?family=Supermercado+One&display=swap"
            rel="stylesheet"
          />
        </Head>

        <main className={styles.main}>
        
          <div className={styles.banner}>
            <Image width={2000} height={500} src={newBan} alt="bannerPic" className={styles.bannerimg} />
          </div>
          <div className={styles.testimonies}>

        
          <div className={styles.reviews}>
            <h1>Our Testimonies </h1>
            <div className={styles.review}>
            
              <hr />
              <div className={styles.float1}>
                <Image
                  className={styles.img}
                  src={dog1}
                  width={300}
                  height={300}
                  alt="bannerPic"
                />
              </div>
              <p>
                <FormatQuoteIcon /> Wufffffff !!! With this App my human found
                my best friend. Thanks to PetTinder I can spend every Weekend
                playing in the park with Corina, My new bestie.
                <FormatQuoteIcon /> <br /> Lucky
              </p>
            </div>
            <div className={styles.review}>
              <hr />
              <div className={styles.float2}>
                <Image
                  className={styles.img}
                  src={dog2}
                  width={300}
                  height={300}
                  alt="bannerPic"
                />
              </div>
              <p>
               
                <FormatQuoteIcon />
                Bark Bark !!! Since I met Billy I have had so much fun. We are
                chasing cats together, fetching ball and even trying many new
                treats! And all that because PeTinder! I would highly recommend
                it to all my paw friends. <FormatQuoteIcon /> <br />
                Rex
              </p>
            </div>
            <hr />
            <div className={styles.review}>
              
              <div className={styles.float1}>
                <Image
                  className={styles.img}
                  src={dog3}
                  width={300}
                  height={300}
                  alt="bannerPic"
                />
              </div>
              <p>
                <FormatQuoteIcon />
                Woof woof! I couldn't be more happy! With PeTinder my human
                friend found my best paw buddy - Lucky. Now my Weekends are sooo
                exciting, I can play with Lucky all day long!
                <FormatQuoteIcon /> <br /> Corina
              </p>
            </div>
            <div className={styles.review}>
              <hr />{" "}
              <div className={styles.float2}>
                <Image
                  className={styles.img}
                  src={dog4}
                  width={300}
                  height={300}
                  alt="bannerPic"
                />
              </div>
              <p>
              
                <FormatQuoteIcon />
                Yeeey! You won't believe how much my life has changed since I met Rex! All the fun stuff we're doing.. woof woof, I'm as happy as ever! Tell your human to get PeTinder right now!   <FormatQuoteIcon />
                <br /> Billy
              </p>
            </div>
          </div>
          </div>

          <div className={styles.advice}>
            <h1> Have we sparked your Interests? </h1>
            <div className={styles.mainAdvices}>
              <div className={styles.advices}>
                <h6>Checklist for New Adopters</h6>
                <p>Help make the transition, as smooth as possible.</p>
                <button onClick={handlePopUps}>Learn More</button>
                <ModalPopUps onClick={popOut} setonClick={setPopOut}>
                  <h5>Checklist</h5>
                  <p>
                    AAAA Lorem Ipsum is simply dummy text of the printing and
                    typesetting industry. Lorem Ipsum has been the industry
                    standard dummy text. Lorem Ipsum is simply dummy text of the
                    printing and typesetting industry. Lorem Ipsum has been the
                    industry standard dummy text{" "}
                  </p>
                </ModalPopUps>
              </div>
              <div className={styles.advices}>
                <h6>COVID-19 Resources</h6>
                <p>
                  Get the latest on adoption processes, learn how local shelters
                  and rescue groups are adapting and find out what you can do to
                  help dogs and cats in need right now.
                </p>
                <button onClick={handlePopUps}>Learn More</button>
                <ModalPopUps onClick={popOut} setonClick={setPopOut}>
                  <h5>COVID-19 Resources</h5>
                  <p>
                    AAAA Lorem Ipsum is simply dummy text of the printing and
                    typesetting industry. Lorem Ipsum has been the industry
                    standard dummy text. Lorem Ipsum is simply dummy text of the
                    printing and typesetting industry. Lorem Ipsum has been the
                    industry standard dummy text{" "}
                  </p>
                </ModalPopUps>
              </div>
              <div className={styles.advices}>
                <h6>PetTinder FAQs</h6>
                <p>Get answers to questions you have not thought of.</p>
                <button onClick={handlePopUps}>Learn More</button>
                <ModalPopUps onClick={popOut} setonClick={setPopOut}>
                  <h5>All You Need To Know</h5>
                  <p>
                    Lorem Ipsum is simply dummy text of the printing and
                    typesetting industry. Lorem Ipsum has been the industry
                    standard dummy text. Lorem Ipsum is simply dummy text of the
                    printing and typesetting industry. Lorem Ipsum has been the
                    industry standard dummy text.
                  </p>
                </ModalPopUps>
              </div>
            </div>
          </div>
        <div className={styles.meetFriend}>
          <PetLink /> 
          <Link href="/Pets">
          <a onClick={handleClick}>
            {" "}
            <button className={styles.viewAllButton}>View All</button>.
          </a>
        </Link>
        </div>
          
        </main>
       
      </div>
    </>
  );
}
