import styles from "../styles/Home.module.css";
import Head from "next/head";

export default function TermsandPrivacy() {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Petinder</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" />
          <link
            href="https://fonts.googleapis.com/css2?family=Supermercado+One&display=swap"
            rel="stylesheet"
          />
        </Head>

        <main className={styles.main}>
          <div>
            Your Privacy Is Important To Us
            <p>
              Please read the terms and policies of Pawmates, as well as the
              privacy policy carefully. <br />
              All data is handled under the terms and policies of Pawmates Terms
              of Use, Privacy Policy, Safety Tips, and FAQs. Thank you 🙂
            </p>
          </div>
        </main>
      </div>
    </>
  );
}
